import { useState } from 'react';
import PageHeader from '../../components/common/PageHeader';
import { Card, CardBody } from '../../components/common/Card';
import Badge from '../../components/common/Badge';
import Button from '../../components/common/Button';
import Note from '../../components/common/Note';
import Icon from '../../components/feedback/Icon';
import { useToast } from '../../context/ToastContext';
import { REPORTS, downloadReport } from '../../services/reportService';
import { USE_MOCK } from '../../services/http';

/**
 * Excel exports.
 *
 * The server exports the FULL table and takes no date or format parameters, so
 * this screen deliberately has no date-range or CSV options — they can be added
 * the day the backend supports them. The Stock Report has no endpoint at all,
 * so its card says so rather than failing on click.
 */
export default function MarketingReports() {
  const toast = useToast();
  const [busy, setBusy] = useState(null);

  const generate = async (report) => {
    setBusy(report.id);
    try {
      const result = await downloadReport(report.id);
      toast.success(result.simulated
        ? `${report.name} would download from ${result.url}`
        : `${report.name} downloaded.`);
    } catch (err) {
      toast.error(err.message);
    } finally {
      setBusy(null);
    }
  };

  return (
    <>
      <PageHeader
        title="Reports"
        sub="Ready-made Excel exports generated by the backend."
      />

      {USE_MOCK && (
        <Note tone="info" className="section">
          Running on demo data — Generate shows the endpoint that would be called instead of downloading a
          file. With the live backend the .xlsx downloads directly.
        </Note>
      )}

      <div className="grid grid--3">
        {REPORTS.map((report) => (
          <Card key={report.id}>
            <CardBody className="stack gap-4">
              <div className="row gap-3">
                <span className={`stat__icon${report.available ? '' : ''}`} style={{ width: 38, height: 38 }}>
                  <Icon name={report.available ? 'download' : 'clock'} size={17} />
                </span>
                <div className="grow">
                  <p style={{ fontWeight: 700 }}>{report.name}</p>
                  {report.available
                    ? <Badge tone="success" dot>Available</Badge>
                    : <Badge tone="muted">Coming soon</Badge>}
                </div>
              </div>

              <p className="subtle" style={{ fontSize: 'var(--fs-sm)' }}>{report.description}</p>

              {report.available ? (
                <>
                  <p className="mono subtle" style={{ fontSize: 'var(--fs-xs)' }}>GET {report.endpoint}</p>
                  <Button variant="primary" icon="download" block loading={busy === report.id}
                    onClick={() => generate(report)}>
                    Generate .xlsx
                  </Button>
                </>
              ) : (
                <>
                  <p className="field__hint">{report.unavailableReason}</p>
                  <Button variant="secondary" block disabled>Not available</Button>
                </>
              )}
            </CardBody>
          </Card>
        ))}
      </div>

      <Note tone="info" className="section" style={{ marginTop: 'var(--sp-6)' }}>
        Each export covers the whole table — the server takes no date-range or format parameters, so there is
        nothing to configure here. Date filtering and CSV output need a backend change first.
      </Note>
    </>
  );
}
